### ISSUE TITLE
void Motor::SetSetpointWithTime(float newTargetInDegrees, float speedDegPerSec) missing in header

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/RBE1001Lib#11]
@gcl8a you forgot to put the prototype in the header, this code didnt compile. 

Can we have a convention that we compile the code before pusing changes?

**Comment by gcl8a** [comment]
Ha! Yes. It’s totally untested. Rookie mistake. Looks like a zero for this assignment...

My mac doesn’t have all the ESP32 stuff on it…but I didn’t think of that when I started doing dev work. I’ll make sure it’s checked in the future.

**Comment by madhephaestus** [comment]
there is a bundled Sloeber for mac withthe compilers. Brad has the issue with the driver figured out, so you should be able to work on you mac if you prefer.
