### ISSUE TITLE
Sample program MotorTest references a missing class

### ISSUE THREAD

**Issue by bradamiller** [WPIRoboticsEngineering/RBE1001Lib#13]
The sample program MotorTest (I assume that that’s the one you wanted people to use) references ESP32Encoder.h which isn’t in the library or available via the Library Manager as a separate library.

**Comment by madhephaestus** [comment]
Hmm, i see it in the library manager and in the installed bundled set of libraries.

Did you install using my installer and use the arduino-rbe or sloeber-rbe?

https://github.com/WPIRoboticsEngineering/RobotInterfaceBoard/blob/master/InstallEclipse.md

Library manager official reference: https://www.arduinolibraries.info/libraries/esp32-encoder

For other IDE's, use the sketchbook in C:\RBE\ArduinoSketchbook as it has all the libraries installed with the bundled installer.

**Comment by madhephaestus** [comment]
Also, check that you have the ESP32 board selected. that library only works with the ESP32 architecture and will be listed as incompatible if a different platform is selected.

**Comment by bradamiller** [comment]
I used VSCode and included RBE1001Lib. And the encoder class isn’t in that library. Then I searched for ESP32Encoder as a library and didn’t find it.

**Comment by bradamiller** [comment]
This is my configuration:
[env:esp32thing]
platform = espressif32
board = esp32thing
framework = arduino
lib_deps = 
    ESP32Servo
    RBE1001Lib

**Comment by madhephaestus** [comment]
It is not in this library, true, it is in the official Arduino Library Manager.

It would seem VSCode is not doing normal things with what libraries are availible to it. 

You will need:
    ESP32Servo
    ESP32AnalogRead
    ESP32Encoder
    RBE1001Lib
    Esp32WifiManager
    ESPmDNS
    FS
    Preferences
    WebServer
    WiFi

**Comment by madhephaestus** [comment]
I also notice you used esp32thing as the board, that is likely the wrong definition, and you should be using the Adafruit ESP32 Feather definition instead. the OG Sparkfun esp32 Thing is from years ago and is not the same thing as what we have. I made an announcement on Canvas to that effect as well.

**Comment by madhephaestus** [comment]
In the future if you want to check if a library is in the Library Manager, open standard Arduino and use the built in Library Manager as ground truth. 

SInce Arduino is the developer and maintainer of the standards, then it is the responsibility of 3rd party plugins such as VS code to adhere to the conventions of the platform. I would post this bug in the VSCode arduino plugin repo instead.
