### ISSUE TITLE
SetSpeed seems to not work correctly

### ISSUE THREAD

**Issue by bradamiller** [WPIRoboticsEngineering/RBE1001Lib#15]
SetSpeed() says it uses values of degrees per second, but it doesn't seem to work for me. A speed of 180 is not close to a half turn per second, it's much smaller.

**Comment by madhephaestus** [comment]
I modified the velocity test to run a long duration speed calculation, verified that set speed matches the speed it is going

**Comment by madhephaestus** [comment]
this bug reintroduced in 2b5f3c85e06dd948ff992cbe2a7995d2a6d05229 

@gcl8a Could you tell us why it was reintroduced after being fixed via c992110602fd303489cec728334e32259f6d257b?

**Comment by madhephaestus** [comment]
nevermind, i misread which function that was in
