### ISSUE TITLE
Ultrasonic interface

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#18]
Can we "go back" to having the ultrasonic just return microseconds? Or at least add a function that does that?

It would make a good, simple exercise for the students to write a function that does the conversion, plus it makes the calibration activity a little more interesting.

**Comment by madhephaestus** [comment]
Rangefinder::getRoundTripTimeMicroSeconds() added and released in 0.3.0
