### ISSUE TITLE
Need better ramping for long movements

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#19]
We have linear and we have sinusoidal interpolations. But for long legs (e.g., the square), it takes a long time to get the wheel up to speed. Can we make a ramp up/ramp down that is more like a trapezoid? Short period to get up to speed; most of the time at constant speed; short ramp down.

**Comment by madhephaestus** [comment]
the sinusoidal interpolation is awkward for long transitions, sure. What is the issue with Linear then? 

Is it jerking off the line and needs to ease off the line more? 

Your MoveFor calls sinusoidal, maybe you want that to call the linear interpolation instead?

**Comment by gcl8a** [comment]
Yeah. llinear is a bit jerky. Probably would have been better to go with that, but I don’t want to change it now.

I did tell the students how to change it in the library, but warned them that they need to know what they’re doing.

**Comment by madhephaestus** [comment]
hmm ok, do you have a specific equation to use to compute the percent completed?

linear is
```
float interpElapsed = (float) (millis() - startTime);
unitDuration = interpElapsed / duration;
```

sinusoidal is

```
float sinPortion = (cos(-PI * unitDuration) / 2) + 0.5;
unitDuration = 1 - sinPortion;
```
where duration and startTime are defined when the interpolation begins, and unitDuration goes from 0 to 1, where 0 represents the position target at the start of the transition, and 1 represents the position at the end of the duration. 

What sort of a unit duration calculation are you looking for?

**Comment by gcl8a** [comment]
Well…I was hoping you had a good idea.

Mathematically, I’d used a trapezoid: ramp linearly from 0 - target speed in N ms; drive at target speed; ramp down from target speed to 0 in N ms.

Programatically, it’s a bit of a pain, since if you put in a time period less than 2N, you have a special case.

Let me think a bit and see if I can come up with a closed-form solution. Certainly easier to just use a linear interpolation in the short term.

**Comment by madhephaestus** [comment]
My first thought is Bezier curve:

https://stackoverflow.com/a/43071667

where the control points are definable through the method call.

**Comment by madhephaestus** [comment]
I added a Quadradic Bezier interpolation mode. Values of 0 and 1 roughly approximates a sinusoidal interpolation, and 0.5 and 1 gives an acceleration off the line and peak velocity higher than sinusoidal, but still ramping up for acceleration and ramp down on deceleration.

**Comment by madhephaestus** [comment]
I also created a trapezoidal interpolation mode. You specify the position and duration of the total transition, as well as how long to spend ramping up and down at the end. In Between the ramping period is linear interpolation. It has a velocity discontinuity at the corners of the trapezoid, so it jerks while driving instead of off the line. Its a bit smoother than linear interpolation, with the higher constant velocity than the sinusoidal mode.

**Comment by madhephaestus** [comment]
@gcl8a could you test to see if one of these new modes meets your request?

**Comment by gcl8a** [comment]
Haven’t tried it yet, but a few questions/comments.

unitDuration is a bit of a misnomer, yes? It’s really the proportion of the target motion that is done — the result of the interpolation. Just trying to make sure I understand it.

Why store startTime as a float? Isn’t uint32_t better, given that it’s a result of millis()?

—

More importantly, the bezier curve you have doesn’t really solve the issue, since the equation is in the “normalized time” coordinate.  BEZIER_P0 would need to change given the duration and amount of the motion; otherwise, you’ll either jump too fast on short durations or long ones will take too long.

One neat way around that is to define a max acceleration at the start (and end). Let v_max be the maximum allowed speed after, say 10 ms. Then you can calculate BEZIER_P0  from,

BEZIER_P0 = duration / (3 * target_angle) * [100 * V_MAX]

(where the 100 is due to the 10 ms).

For a given duration, a larger motion will result in a lower value of BEZIER_P0, which will lower the speed in the normalized timeframe, resulting the correct speed in real time. Other thought experiments will show the correct behaviour.

(I’m guessing Spong has something to this effect — I derived it independently, so take it for what that’s worth.)

Also, the curve is symmetric if BEZIER_P0 = 1 - BEZIER_P1, so you only need calculate the one.

Greg

**Comment by gcl8a** [comment]
I think my Bezier interpretation is only half-correct -- need to think about it more. I'm guessing you have bigger fish to fry, so file this one under "mental exercises" and we can revisit later. Probably best to just use LINEAR interpolation (or your trapezoid, which I haven't done much with, yet).
