### ISSUE TITLE
Coordinates/right.left.front.back

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#26]
For A-term, let's define the coordinate system for the Romi once and for all and get everything all coordinated. Obviously, we can't change things now, but the motors are not coordinated on the web server.

- line sensors go on the front
- ultrasonic faces front (or pick a side for wall following)
- lifting arm faces front
- motors are renamed motorL and motorR
- positive rotation of motors moves the robot forward
- web server accurately reflects the motors
- side note: change angle on the web server to speed (easy enough)

**Comment by madhephaestus** [comment]
as a note, you can keep adding more things to display, its a dynamic list. 

```
buttonPage.setValue("Right Motor degrees",
								motor2.getCurrentDegrees());
```

is called in the polling loop, so you can add more lines if you want. 

It works on the principal of key/value mapping. the string is both key, and a displayed string. The key has a value that can be set and reset. We have plenty of ram, so you can add lots of values.

**Comment by madhephaestus** [comment]
The quick fix was to change the scaling factor to negative. 

As fo whats displayed, pull the lastest Master to check the updated labels and forward direction.
