### ISSUE TITLE
Jumping when uploading

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#27]
When uploading to the ESP32, the motors will spin momentarily, as if it is running the last program for a short period of time.

**Comment by madhephaestus** [comment]
is this while the upload is writing, or before that? 

Generally its a good practice to always set the motors to disabled while programming.

**Comment by gcl8a** [comment]
Right around when it starts to upload. It’s not realistic to have them plug the wire in everytime (and not possible with the shim board). We need a failsafe.

**Comment by madhephaestus** [comment]
We should go over your wiring, i can not reproduce the problem on my hardware. Is it that your program has it run right off the boot? What INO is causing this behavior?

FYI: the shim has a jumper for motor disable right near the user sensor headers and it it easy to get to.

**Comment by gcl8a** [comment]
I think I discovered what the issue is: when it first starts to upload, it does something to the BOOT pin. But I use the BOOT button for gatekeeping:

while(!digitialRead(0)) {}

So when it gets ready to upload, a button signal will get sent, the code will run for, say, half a second, then the upload will start.

**Comment by madhephaestus** [comment]
AH, are you explicitly setting the button to INPUT_PULLUP? There is no external pull up on that pin, so it may be that the reset on program clears the Pullup from the internal bootloader use of the pin, causing it to move.
