### ISSUE TITLE
Add PID tuning to web server?

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#28]
I realize it's recreating the filed controller, but a page on the web server, .../motors, could be useful for tuning the motors. I'm surprised how much difference they have, though, so no single defaults are going to work for everyone.

I could see fields for K and then a button to make the wheel spin once or something like that. They don't need to tune to perfection, but at least get rid of the jitters. This would save a lot of uploading test codes -- easily the single biggest time saver of the field controller.

**Comment by madhephaestus** [comment]
duplicate to #9
