### ISSUE TITLE
SetEffort() has odd behavior

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#29]
More than one student has had the situation where SetEffort(0.99) does nothing, but SetEffort(1) goes full speed. The function takes a float as an argument, so I'm at a loss. Not sure if anyone else can re-create the problem -- mine works fine!

**Comment by madhephaestus** [comment]
have students with this issue contact me, i cat reproduce it either.

**Comment by gcl8a** [comment]
This one I could never reproduce. I did notice that my SetEffort() code never called pwm->writeScaled(abs(effort)); But then I don’t understand how it ever worked.

**Comment by madhephaestus** [comment]
read encoders and write PWM are only ever called by the tread for timing, and also for collision avoidance in method calls. They set values that are actually loaded to the PWM by the thread. 

THis also avoids the read too fast, write too fast issues, because the thread gates access to the hardware from the user so they need not worry about how fast they set anything.

**Comment by gcl8a** [comment]
Does that mean that all one needs to do is set currentEffort and that will get sent to the PWM? I don’t see where that happens.

**Comment by madhephaestus** [comment]
when you call set effort:
https://github.com/WPIRoboticsEngineering/RBE1001Lib/blob/0.5.4/src/Motor.cpp#L364

it sets the effort value to currentEffort but also sets closedLoopControl to false.

when the PID thread calls loop on the motor here:
https://github.com/WPIRoboticsEngineering/RBE1001Lib/blob/0.5.4/src/Motor.cpp#L88

it will then go and read the encoder every time, and check 

https://github.com/WPIRoboticsEngineering/RBE1001Lib/blob/0.5.4/src/Motor.cpp#L271 

closedLoopControl to see if effort is to be recomputed, if not it passes the effort along to the private method SetEffortLocal 

https://github.com/WPIRoboticsEngineering/RBE1001Lib/blob/0.5.4/src/Motor.cpp#L391

which will set the PWM
