### ISSUE TITLE
Motor definitions

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#32]
Let’s start by defining:

- The front of the robot is the end with the line sensor, which (from last I knew) is the end with the sprung caster.
- Then left and right are given.
- Then each wheel should go positive when the robot moves forward
- Can we make the motors in the examples, motorLeft and motorRight?
- Can we make it so you have to push the button to get the wheels to start? (That way the robot doesn't drive off if they forget the jumper.)

**Comment by gcl8a** [comment]
Follow-up: Not sure what's being updated -- I know Kevin is looking into it -- but the motors are reversed on the web-page dashboard. Also, what is "encoder effort"? (Also, it should be deg/sec, not deg-sec)

**Comment by madhephaestus** [comment]
link to where "encoder effort" shows up?

**Comment by madhephaestus** [comment]
Ah, found it, strings in the example
