### ISSUE TITLE
RCCTL issues

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#33]
- At least for my ESP32, it loses the network ID on reset/upload. I have to reconnect every time.

Wish list: 
- The interface for entering networks is a little clunky. 
-- It's unclear if you have to hit ENTER (and if you do, it takes a null password and you have to restart)
-- the counting business is confusing -- what is it counting for? It never connects anyway.
-- It'd be really nice if you could just type the number of the network and not the full name (it took me a bit to figure out that I couldn't). But if it would actually remember my network, then that's unimportant.

**Comment by gcl8a** [comment]
Follow-up: the problem persists with a different ESP32 and with the latest code (in the rc-pid-graph branch).

I can shoot a Serial Monitor capture if that helps.

**Comment by madhephaestus** [comment]
i wonder if its something about the network name or password...

in any case the output from the serial monitor as it finally connects might be helpful, just take a look and make sure you dont post your password ;)

**Comment by gcl8a** [comment]
After hitting RESET:

--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at http://bit.ly/pio-monitor-filters
--- Miniterm on /dev/cu.SLAB_USBtoUART  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: MySpectrumWiFi02-2G NOT_FOUND
connect to WiFi network
Attempting to connect to WiFi network: MySpectrumWiFi02-2GSYSTEM_EVENT_AP_START

SYSTEM_EVENT_STA_STOP
SYSTEM_EVENT_STA_STOP
Mac Address: 24:6F:28:80:37:E8
Waiting for WIFI connection... 


ESP32 WiFi ready 
WifiManager.getState()=Disconnected


WiFi lost connection, retry 1
SYSTEM_EVENT_STA_STOP
Timeouts for connection wait, reconnecting last connected: 0 last disconnected: 4613 now 14614
WifiManager.getState()=reconnect
connect to WiFi network
Attempting to connect to WiFi network: MySpectrumWiFi02-2G
ESP32 WiFi ready 
SYSTEM_EVENT_STA_STOP
SYSTEM_EVENT_STA_STOP
Mac Address: 24:6F:28:80:37:E8
Waiting for WIFI connection... 


ESP32 WiFi ready 
WifiManager.getState()=Disconnected


WiFi lost connection, retry 0
SYSTEM_EVENT_STA_STOP
Timeouts for connection wait, reconnecting last connected: 0 last disconnected: 19115 now 29116
WifiManager.getState()=reconnect
scan start
ESP32 WiFi ready 
SYSTEM_EVENT_STA_STOP
SYSTEM_EVENT_STA_STOP
ESP32 WiFi ready 
SYSTEM_EVENT_SCAN_DONE
scan DONE!
14 networks found
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: MySpectrumWiFi02-2G NOT_FOUND
 Default AP is missing, searching for new one
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: MySpectrumWiFi02-2G NOT_FOUND
: MySpectrumWiFi02-2G (-53)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: Ddooomm NOT_FOUND
2: Ddooomm (-76)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: J&S NOT_FOUND
3: J&S (-84)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: MySpectrumWiFib3-2G NOT_FOUND
4: MySpectrumWiFib3-2G (-84)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: J&S NOT_FOUND
5: J&S (-85)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: Santiago Ramon y Cajal NOT_FOUND
6: Santiago Ramon y Cajal (-87)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: Santiago Ramon y Cajal NOT_FOUND
7: Santiago Ramon y Cajal (-88)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: J&S NOT_FOUND
8: J&S (-89)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: NETGEAR90 NOT_FOUND
9: NETGEAR90 (-89)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: NETGEAR47 NOT_FOUND
10: NETGEAR47 (-91)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: NETGEAR81 NOT_FOUND
11: NETGEAR81 (-93)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: DLA NOT_FOUND
12: DLA (-93)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: Santiago Ramon y Cajal NOT_FOUND
13: Santiago Ramon y Cajal (-94)*
[E][Preferences.cpp:437] getString(): nvs_get_str len fail: Ardit's Wi-Fi Network NOT_FOUND
14: Ardit's Wi-Fi Network (-94)*

NO availible AP/Pass stored



AP starting esp32-37-E8
ESP32 WiFi ready 
Mac Address: 24:6F:28:80:37:E8
SYSTEM_EVENT_STA_STOP
SYSTEM_EVENT_AP_START
Starting AP:esp32-37-E8
pass = Wumpus3742
SYSTEM_EVENT_AP_START
Waiting for client to connect to AP 2

**Comment by madhephaestus** [comment]
```
[E][Preferences.cpp:251] putString(): nvs_set_str fail: MySpectrumWiFi02-2G KEY_TOO_LONG
```
Nuts. It looks like there is a 15 char limit on storing arbitrary strings :( 

Workaround 1:
 change the SSID to something shorter than 15 chars
Workaround 2:
 use the built in AP mode failover. If you change manager.setup() to manager.setupAP() it will host its own wifi network, and the student connects with their phone. We could make this the standard to prevent such a problem
Workaround 3:
 enter your password every time you reboot the ESP

Semi-Solution:
 Detect that the AP name is to long and print a more aggressive error message. I will also do a string prune to ensure that the string that is stored is the substring of the first 15 chars of the SSID name, but this can be brittle an break especially on auto generated SSID's since the last few chars are the unique part. Maybe ill just take the last 15 if the string is over 15. [Ill have to look into this in that library.](https://github.com/madhephaestus/Esp32WifiManager/issues/6)

**Comment by madhephaestus** [comment]
Update Esp32WifiManager to version 0.13.0 and this will be fixed.

**Comment by gcl8a** [comment]
Is that a release? Or I just need to go to the repo?

**Comment by madhephaestus** [comment]
i *just* made a release, itll be a bit before it percolates through. You can replace the library manager version with a git checkout, same way you did with this library. It would be faster than waiting ;)

**Comment by gcl8a** [comment]
That worked. And it only took me a few seconds to edit my platformio.ino file to grab the latest…   ;-)

I’ll check it occasionally to see how long it takes to get the release.
