### ISSUE TITLE
lowercase methods

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#34]
When motor.cpp/h are stable (ie, I don't want to create merge conflicts), I will go in and change my functions to classis camelCase. My habit of Capitalizing functions is too confusing. Just let me know a good time to do it.

**Comment by madhephaestus** [comment]
Ill assign this issue to you, you change it and put this issue number in the commit and close. I will not touch Motor until this is closed.

**Comment by madhephaestus** [comment]
Alternatively you can assign it to me and ill go and poke the method names

**Comment by gcl8a** [comment]
I’m doing it now. Almost done.

**Comment by gcl8a** [comment]
It's done. I tested all of the examples, but it's possible I missed something. Let me know if you encounter any problems.

I think you deleted FullSystemTest -- I had a merge conflict. I put it back in, only because I don't want to clobber our example until you're ready. We should save the FullSystemTest for our use (in a private repo?).

**Comment by madhephaestus** [comment]
with the updated API. lets tag a version, then delete it. The code is there for our use for reference, but will be gone out of the students examples.

**Comment by madhephaestus** [comment]
its will always be here: https://github.com/WPIRoboticsEngineering/RBE1001Lib/blob/0.7.1/examples/FullSystemTest/FullSystemTest.ino

**Comment by gcl8a** [comment]
Got it. I know it’s all in the history — I’m just not always confident about how to go back in time.

And please excuse if I missed any function names. Everything seemed to compile, but you never know. Better to clean it all up now, obviously, than during the term.
