### ISSUE TITLE
Careful not to swap the encoder lines on left motor

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/RBE1001Lib#37]
@gcl8a Is using a V2 board, that has left motor encoder lines swapped. Be sure not to commit that to GIthub, and use right motor for testing. 

Alternately, if you change it in the RBE1001Lib.h, then in git you can mark it as assume unchanged, so those changes don't get committed.

**Comment by gcl8a** [comment]
Got it. I thought that might be the case. I can make sure that doesn’t happen in the future.

**Comment by gcl8a** [comment]
Please change the values to the V3 board. I'll change things safely on my end.
