### ISSUE TITLE
Turning backwards?

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#39]
On my Romi, the turning is backwards: moving the dot left makes it turn right.

I do have different encoders, but only on one side -- I fail to see how this would affect that.

**Comment by madhephaestus** [comment]
is this an RCCTL question?

**Comment by gcl8a** [comment]
Sorry. Yes. The interactive web page.

**Comment by madhephaestus** [comment]
ok, fixed now 0.9.4
