### ISSUE TITLE
Create test for web control

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/RBE1001Lib#5]

**Comment by gcl8a** [comment]
What is the overall status of "teleop"? Brad's server app (running on the ESP) has some basic buttons, but no real control. It's important to have something akin to a joystick-like interface. Something that allows you to turn a little bit, drive a little bit, etc. Some kind of fine-tune control.

Ideally, it could run on the ESP and just serve up an interface -- simpler that way. 

Perhaps something like four arrows and so long as you click and hold on them, they engage the motors. Alternatively, individual clicks add/subtract from the current setpoints (with a STOP in the middle).

**Comment by madhephaestus** [comment]
this issue is being addressed in Pull Request #17 Brads server was a 1 second poll stack, @acamilo  is using his experience setting up web sockets on the ESP to convert it to a low latency RC control.

**Comment by gcl8a** [comment]
Do we have a status update? (Sorry, I don't know if I should post that here or on #17, itself).

**Comment by madhephaestus** [comment]
the async server is installed under Brads old API and makes it stable and also 10x faster on polling. Updates come in once every 100ms now.

@acamilo  and I are working switching from polling to websockets and adding the joystick code. We will have a final release at 5 that will bring us up to 10ms update rate, which is finally fast enough for RC control.
